export type PassageCategory = 'movies-tv' | 'speeches' | 'idioms' | 'tongue-twisters' | 'literature' | 'essays' | 'custom'

export const PASSAGE_CATEGORIES: PassageCategory[] = ['movies-tv', 'speeches', 'idioms', 'tongue-twisters', 'literature', 'essays', 'custom']

export const CATEGORY_LABELS: Record<PassageCategory, string> = {
  'movies-tv': 'Movie & TV Quotes',
  'speeches': 'Famous Speeches',
  'idioms': 'Idioms',
  'tongue-twisters': 'Tongue Twisters',
  'literature': 'Literature',
  'essays': 'Essays',
  'custom': 'Custom',
}

export interface Passage {
  id: string
  title: string
  source: string
  text: string
  category: PassageCategory
  ipa?: Record<string, string>
  youtubeId?: string
  youtubeStart?: number
  youtubeEnd?: number
}

export const SAMPLE_PASSAGES: Passage[] = [
  {
    id: 'interstellar',
    title: 'Interstellar',
    source: 'Christopher Nolan, 2014',
    category: 'movies-tv',
    text: "We used to look up at the sky and wonder at our place in the stars. Now we just look down, and worry about our place in the dirt.",
    youtubeId: 'MIDrL5zRwxU',
    youtubeStart: 59,
    youtubeEnd: 72,
    ipa: {
      we: '/wiː/',
      used: '/juːzd/',
      to: '/tuː/',
      look: '/lʊk/',
      up: '/ʌp/',
      at: '/æt/',
      the: '/ðə/',
      sky: '/skaɪ/',
      and: '/ænd/',
      wonder: '/ˈwʌndər/',
      our: '/aʊər/',
      place: '/pleɪs/',
      in: '/ɪn/',
      stars: '/stɑːrz/',
      now: '/naʊ/',
      just: '/dʒʌst/',
      down: '/daʊn/',
      worry: '/ˈwɜːri/',
      about: '/əˈbaʊt/',
      dirt: '/dɜːrt/',
    },
  },
  {
    id: 'great-dictator',
    title: 'The Great Dictator',
    source: 'Charlie Chaplin, 1940',
    category: 'movies-tv',
    text: "You, the people, have the power to make this life free and beautiful, to make this life a wonderful adventure. Let us fight to free the world, to do away with national barriers, to do away with greed, with hate and intolerance. Let us fight for a world of reason, a world where science and progress will lead to all men's happiness.",
    ipa: {
      you: '/juː/',
      the: '/ðə/',
      people: '/ˈpiːpəl/',
      have: '/hæv/',
      power: '/ˈpaʊər/',
      make: '/meɪk/',
      this: '/ðɪs/',
      life: '/laɪf/',
      free: '/friː/',
      and: '/ænd/',
      beautiful: '/ˈbjuːtɪfəl/',
      wonderful: '/ˈwʌndərfəl/',
      adventure: '/ədˈventʃər/',
      let: '/lɛt/',
      us: '/ʌs/',
      fight: '/faɪt/',
      world: '/wɜːrld/',
      do: '/duː/',
      away: '/əˈweɪ/',
      with: '/wɪð/',
      national: '/ˈnæʃənəl/',
      barriers: '/ˈbæriərz/',
      greed: '/ɡriːd/',
      hate: '/heɪt/',
      intolerance: '/ɪnˈtɒlərəns/',
      for: '/fɔːr/',
      reason: '/ˈriːzən/',
      where: '/wɛr/',
      science: '/ˈsaɪəns/',
      progress: '/ˈprɒɡrɛs/',
      will: '/wɪl/',
      lead: '/liːd/',
      all: '/ɔːl/',
      happiness: '/ˈhæpɪnəs/',
    },
  },
  {
    id: 'rocky-balboa',
    title: 'Rocky Balboa',
    source: 'Sylvester Stallone, 2006',
    category: 'movies-tv',
    text: "Let me tell you something you already know. The world ain't all sunshine and rainbows, it's a very mean and nasty place and I don't care how tough you are it will beat you to your knees and keep you there permanently if you let it. You, me, nobody is gonna hit as hard as life! But it ain't about how hard you can hit, it's about how hard you can get hit and keep movin' forward, how much you can take...and keep movin' forward. That's how winning is done!",
    youtubeId: 'D_Vg4uyYwEk',
    youtubeStart: 98,
    youtubeEnd: 127,
    ipa: {
      let: '/lɛt/',
      me: '/miː/',
      tell: '/tɛl/',
      you: '/juː/',
      something: '/ˈsʌmθɪŋ/',
      already: '/ɔːlˈrɛdi/',
      know: '/noʊ/',
      the: '/ðə/',
      world: '/wɜːrld/',
      all: '/ɔːl/',
      sunshine: '/ˈsʌnʃaɪn/',
      and: '/ænd/',
      rainbows: '/ˈreɪnboʊz/',
      very: '/ˈvɛri/',
      mean: '/miːn/',
      nasty: '/ˈnæsti/',
      place: '/pleɪs/',
      care: '/kɛr/',
      how: '/haʊ/',
      tough: '/tʌf/',
      beat: '/biːt/',
      knees: '/niːz/',
      keep: '/kiːp/',
      permanently: '/ˈpɜːrmənəntli/',
      nobody: '/ˈnoʊbədi/',
      gonna: '/ˈɡɒnə/',
      hit: '/hɪt/',
      hard: '/hɑːrd/',
      life: '/laɪf/',
      but: '/bʌt/',
      about: '/əˈbaʊt/',
      forward: '/ˈfɔːrwərd/',
      much: '/mʌtʃ/',
      take: '/teɪk/',
      winning: '/ˈwɪnɪŋ/',
      done: '/dʌn/',
    },
  },
  {
    id: 'steve-jobs-stanford',
    title: 'Stanford Commencement',
    source: 'Steve Jobs, 2005',
    category: 'speeches',
    text: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma, which is living with the results of other people's thinking. Don't let the noise of others' opinions drown out your own inner voice. And most importantly, have the courage to follow your heart and intuition.",
    ipa: {
      your: '/jɔːr/',
      time: '/taɪm/',
      is: '/ɪz/',
      limited: '/ˈlɪmɪtɪd/',
      so: '/soʊ/',
      "don't": '/doʊnt/',
      waste: '/weɪst/',
      it: '/ɪt/',
      living: '/ˈlɪvɪŋ/',
      someone: '/ˈsʌmwʌn/',
      else: '/ɛls/',
      life: '/laɪf/',
      be: '/biː/',
      trapped: '/træpt/',
      by: '/baɪ/',
      dogma: '/ˈdɒɡmə/',
      which: '/wɪtʃ/',
      results: '/rɪˈzʌlts/',
      of: '/ʌv/',
      other: '/ˈʌðər/',
      people: '/ˈpiːpəl/',
      thinking: '/ˈθɪŋkɪŋ/',
      let: '/lɛt/',
      the: '/ðə/',
      noise: '/nɔɪz/',
      opinions: '/əˈpɪnjənz/',
      drown: '/draʊn/',
      out: '/aʊt/',
      own: '/oʊn/',
      inner: '/ˈɪnər/',
      voice: '/vɔɪs/',
      and: '/ænd/',
      most: '/moʊst/',
      importantly: '/ɪmˈpɔːrtəntli/',
      have: '/hæv/',
      courage: '/ˈkɜːrɪdʒ/',
      to: '/tuː/',
      follow: '/ˈfɒloʊ/',
      heart: '/hɑːrt/',
      intuition: '/ˌɪntjuˈɪʃən/',
    },
  },
  {
    id: 'inigo-montoya',
    title: 'The Princess Bride',
    source: 'William Goldman, 1987',
    category: 'movies-tv',
    text: "Hello. My name is Inigo Montoya. You killed my father. Prepare to die. I have been in the revenge business so long, now that it's over, I do not know what to do with the rest of my life.",
    ipa: {
      hello: '/həˈloʊ/',
      my: '/maɪ/',
      name: '/neɪm/',
      is: '/ɪz/',
      inigo: '/ˈɪnɪɡoʊ/',
      montoya: '/mɒnˈtɔɪə/',
      you: '/juː/',
      killed: '/kɪld/',
      father: '/ˈfɑːðər/',
      prepare: '/prɪˈpɛr/',
      to: '/tuː/',
      die: '/daɪ/',
      i: '/aɪ/',
      have: '/hæv/',
      been: '/bɪn/',
      in: '/ɪn/',
      the: '/ðə/',
      revenge: '/rɪˈvɛndʒ/',
      business: '/ˈbɪznɪs/',
      so: '/soʊ/',
      long: '/lɒŋ/',
      now: '/naʊ/',
      that: '/ðæt/',
      it: '/ɪt/',
      over: '/ˈoʊvər/',
      do: '/duː/',
      not: '/nɒt/',
      know: '/noʊ/',
      what: '/wʌt/',
      with: '/wɪð/',
      rest: '/rɛst/',
      of: '/ʌv/',
      life: '/laɪf/',
    },
  },
  {
    id: 'i-have-a-dream',
    title: 'I Have a Dream',
    source: 'Martin Luther King Jr., 1963',
    category: 'speeches',
    text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed: we hold these truths to be self-evident, that all men are created equal. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.",
    ipa: {
      i: '/aɪ/',
      have: '/hæv/',
      a: '/ə/',
      dream: '/driːm/',
      that: '/ðæt/',
      one: '/wʌn/',
      day: '/deɪ/',
      this: '/ðɪs/',
      nation: '/ˈneɪʃən/',
      will: '/wɪl/',
      rise: '/raɪz/',
      up: '/ʌp/',
      and: '/ænd/',
      live: '/lɪv/',
      out: '/aʊt/',
      the: '/ðə/',
      true: '/truː/',
      meaning: '/ˈmiːnɪŋ/',
      of: '/ʌv/',
      its: '/ɪts/',
      creed: '/kriːd/',
      we: '/wiː/',
      hold: '/hoʊld/',
      these: '/ðiːz/',
      truths: '/truːθs/',
      to: '/tuː/',
      be: '/biː/',
      self: '/sɛlf/',
      evident: '/ˈɛvɪdənt/',
      all: '/ɔːl/',
      men: '/mɛn/',
      are: '/ɑːr/',
      created: '/kriˈeɪtɪd/',
      equal: '/ˈiːkwəl/',
      my: '/maɪ/',
      four: '/fɔːr/',
      little: '/ˈlɪtəl/',
      children: '/ˈtʃɪldrən/',
      in: '/ɪn/',
      where: '/wɛr/',
      not: '/nɒt/',
      judged: '/dʒʌdʒd/',
      by: '/baɪ/',
      color: '/ˈkʌlər/',
      their: '/ðɛr/',
      skin: '/skɪn/',
      but: '/bʌt/',
      content: '/ˈkɒntɛnt/',
      character: '/ˈkærɪktər/',
    },
  },
  {
    id: 'she-sells-seashells',
    title: 'She Sells Seashells',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "She sells seashells by the seashore. The shells she sells are surely seashells. So if she sells shells on the seashore, I'm sure she sells seashore shells.",
    ipa: {
      she: '/ʃiː/',
      sells: '/sɛlz/',
      seashells: '/ˈsiːʃɛlz/',
      by: '/baɪ/',
      the: '/ðə/',
      seashore: '/ˈsiːʃɔːr/',
      shells: '/ʃɛlz/',
      are: '/ɑːr/',
      surely: '/ˈʃʊərli/',
      so: '/soʊ/',
      if: '/ɪf/',
      on: '/ɒn/',
      sure: '/ʃʊər/',
    },
  },
  {
    id: 'peter-piper',
    title: 'Peter Piper',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where's the peck of pickled peppers Peter Piper picked?",
    ipa: {
      peter: '/ˈpiːtər/',
      piper: '/ˈpaɪpər/',
      picked: '/pɪkt/',
      a: '/ə/',
      peck: '/pɛk/',
      of: '/ʌv/',
      pickled: '/ˈpɪkəld/',
      peppers: '/ˈpɛpərz/',
      if: '/ɪf/',
      where: '/wɛr/',
      the: '/ðə/',
    },
  },
  {
    id: 'woodchuck',
    title: 'How Much Wood',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.",
    ipa: {
      how: '/haʊ/',
      much: '/mʌtʃ/',
      wood: '/wʊd/',
      would: '/wʊd/',
      a: '/ə/',
      woodchuck: '/ˈwʊdtʃʌk/',
      chuck: '/tʃʌk/',
      if: '/ɪf/',
      could: '/kʊd/',
      he: '/hiː/',
      as: '/æz/',
      and: '/ænd/',
    },
  },
  {
    id: 'old-man-sea',
    title: 'The Old Man and the Sea',
    source: 'Ernest Hemingway, 1952',
    category: 'literature',
    text: "He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish. Each day was the same as the one before.",
    ipa: {
      he: '/hiː/',
      was: '/wəz/',
      an: '/ən/',
      old: '/oʊld/',
      man: '/mæn/',
      who: '/huː/',
      fished: '/fɪʃt/',
      alone: '/əˈloʊn/',
      in: '/ɪn/',
      skiff: '/skɪf/',
      the: '/ðə/',
      gulf: '/ɡʌlf/',
      stream: '/striːm/',
      and: '/ænd/',
      had: '/hæd/',
      gone: '/ɡɔːn/',
      eighty: '/ˈeɪti/',
      four: '/fɔːr/',
      days: '/deɪz/',
      now: '/naʊ/',
      without: '/wɪðˈaʊt/',
      taking: '/ˈteɪkɪŋ/',
      fish: '/fɪʃ/',
      each: '/itʃ/',
      day: '/deɪ/',
      is: '/ɪz/',
      same: '/seɪm/',
      one: '/wʌn/',
      before: '/bɪˈfɔːr/',
    },
  },
  {
    id: 'politics-language',
    title: 'Politics and the English Language',
    source: 'George Orwell, 1946',
    category: 'essays',
    text: "The great enemy of clear language is insincerity. When there is a gap between one's real and one's declared aims, one turns, as it were, to long words and exhausted idioms, like a cuttlefish squirting out ink.",
    ipa: {
      the: '/ðə/',
      great: '/ɡreɪt/',
      enemy: '/ˈɛnəmi/',
      of: '/ʌv/',
      clear: '/klɪr/',
      language: '/ˈlæŋɡwɪdʒ/',
      is: '/ɪz/',
      insincerity: '/ˌɪnsɪnˈsɛrɪti/',
      when: '/wɛn/',
      there: '/ðɛr/',
      gap: '/ɡæp/',
      between: '/bɪˈtwiːn/',
      one: '/wʌn/',
      real: '/riːəl/',
      declared: '/dɪˈklɛrd/',
      aims: '/eɪmz/',
      turns: '/tɜːrnz/',
      as: '/æz/',
      it: '/ɪt/',
      were: '/wɜːr/',
      to: '/tuː/',
      long: '/lɔːŋ/',
      words: '/wɜːrdz/',
      and: '/ænd/',
      exhausted: '/ɪɡˈzɔːstɪd/',
      idioms: '/ˈɪdiəmz/',
      like: '/laɪk/',
      cuttlefish: '/ˈkʌtəlˌfɪʃ/',
      squirting: '/ˈskwɜːrtɪŋ/',
      out: '/aʊt/',
      ink: '/ɪŋk/',
    },
  },
  {
    id: 'dorian-gray',
    title: 'The Picture of Dorian Gray',
    source: 'Oscar Wilde, 1890',
    category: 'literature',
    text: "There is no such thing as a moral or an immoral book. Books are well written or badly written. That is all. The truth is rarely pure and never simple. Modern life is complex.",
    ipa: {
      there: '/ðɛr/',
      is: '/ɪz/',
      no: '/noʊ/',
      such: '/sʌtʃ/',
      thing: '/θɪŋ/',
      as: '/æz/',
      a: '/ə/',
      moral: '/ˈmɔːrəl/',
      or: '/ɔːr/',
      an: '/ən/',
      immoral: '/ɪˈmɔːrəl/',
      book: '/bʊk/',
      books: '/bʊks/',
      are: '/ɑːr/',
      well: '/wɛl/',
      written: '/ˈrɪtən/',
      badly: '/ˈbædli/',
      that: '/ðæt/',
      all: '/ɔːl/',
      truth: '/truːθ/',
      rarely: '/ˈrɛrli/',
      pure: '/pjʊər/',
      and: '/ænd/',
      never: '/ˈnɛvər/',
      simple: '/ˈsɪmpəl/',
      modern: '/ˈmɒdərn/',
      life: '/laɪf/',
      complex: '/ˈkɒmplɛks/',
    },
  },
  {
    id: 'break-a-leg',
    title: 'Break a leg',
    source: 'Common idiom',
    category: 'idioms',
    text: "Break a leg! This phrase is what you say to someone before they perform, like before a theatre show or concert. It actually means good luck, even though it sounds like you're wishing them harm.",
    ipa: {
      break: '/breɪk/',
      a: '/ə/',
      leg: '/lɛɡ/',
      phrase: '/freɪz/',
      is: '/ɪz/',
      what: '/wʌt/',
      you: '/juː/',
      say: '/seɪ/',
      to: '/tuː/',
      someone: '/ˈsʌmwʌn/',
      before: '/bɪˈfɔːr/',
      they: '/ðeɪ/',
      perform: '/pərˈfɔːrm/',
      like: '/laɪk/',
      theatre: '/ˈθiːətər/',
      show: '/ʃoʊ/',
      or: '/ɔːr/',
      concert: '/ˈkɑːnsərt/',
      actually: '/ˈæktʃuəli/',
      means: '/miːnz/',
      good: '/ɡʊd/',
      luck: '/lʌk/',
      even: '/ˈiːvən/',
      though: '/ðoʊ/',
      sounds: '/saʊndz/',
      wishing: '/ˈwɪʃɪŋ/',
      them: '/ðɛm/',
      harm: '/hɑːrm/',
    },
  },
  {
    id: 'burn-midnight-oil',
    title: 'Burn the midnight oil',
    source: 'Common idiom',
    category: 'idioms',
    text: "When you burn the midnight oil, you work very late into the night. Students often burn the midnight oil when studying for exams. The phrase comes from when people used oil lamps to work after dark.",
    ipa: {
      when: '/wɛn/',
      you: '/juː/',
      burn: '/bɜːrn/',
      the: '/ðə/',
      midnight: '/ˈmɪdnaɪt/',
      oil: '/ɔɪl/',
      work: '/wɜːrk/',
      very: '/ˈvɛri/',
      late: '/leɪt/',
      into: '/ˈɪntuː/',
      night: '/naɪt/',
      students: '/ˈstuːdənts/',
      often: '/ˈɔːfən/',
      studying: '/ˈstʌdiɪŋ/',
      for: '/fɔːr/',
      exams: '/ɪɡˈzæmz/',
      phrase: '/freɪz/',
      comes: '/kʌmz/',
      from: '/frʌm/',
      people: '/ˈpiːpəl/',
      used: '/juːzd/',
      lamps: '/læmps/',
      after: '/ˈæftər/',
      dark: '/dɑːrk/',
    },
  },
  {
    id: 'caught-red-handed',
    title: 'Caught red-handed',
    source: 'Common idiom',
    category: 'idioms',
    text: "If you're caught red-handed, you are discovered doing something wrong or dishonest. There's no way to deny it because you are caught in the act. The red refers to blood from your wrongdoing.",
    ipa: {
      if: '/ɪf/',
      you: '/juː/',
      caught: '/kɔːt/',
      red: '/rɛd/',
      handed: '/ˈhændɪd/',
      are: '/ɑːr/',
      discovered: '/dɪˈskʌvərd/',
      doing: '/ˈduːɪŋ/',
      something: '/ˈsʌmθɪŋ/',
      wrong: '/rɔːŋ/',
      or: '/ɔːr/',
      dishonest: '/dɪsˈɒnɪst/',
      there: '/ðɛr/',
      is: '/ɪz/',
      no: '/noʊ/',
      way: '/weɪ/',
      to: '/tuː/',
      deny: '/dɪˈnaɪ/',
      it: '/ɪt/',
      because: '/bɪˈkɔːz/',
      in: '/ɪn/',
      the: '/ðə/',
      act: '/ækt/',
      refers: '/rɪˈfɜːrz/',
      blood: '/blʌd/',
      from: '/frʌm/',
      your: '/jɔːr/',
      wrongdoing: '/ˈrɔːŋˌduːɪŋ/',
    },
  },
  {
    id: 'elephant-in-room',
    title: 'The elephant in the room',
    source: 'Common idiom',
    category: 'idioms',
    text: "The elephant in the room is a problem or situation that everyone notices but no one wants to talk about. It's obvious and hard to ignore, like a giant elephant standing in a small room.",
    ipa: {
      the: '/ðə/',
      elephant: '/ˈɛləfənt/',
      in: '/ɪn/',
      room: '/ruːm/',
      is: '/ɪz/',
      a: '/ə/',
      problem: '/ˈprɒbləm/',
      or: '/ɔːr/',
      situation: '/ˌsɪtʃuˈeɪʃən/',
      that: '/ðæt/',
      everyone: '/ˈɛvriˌwʌn/',
      notices: '/ˈnoʊtɪsɪz/',
      but: '/bʌt/',
      no: '/noʊ/',
      one: '/wʌn/',
      wants: '/wɑːnts/',
      to: '/tuː/',
      talk: '/tɔːk/',
      about: '/əˈbaʊt/',
      it: '/ɪt/',
      obvious: '/ˈɒbviəs/',
      and: '/ænd/',
      hard: '/hɑːrd/',
      ignore: '/ɪɡˈnɔːr/',
      like: '/laɪk/',
      giant: '/ˈdʒaɪənt/',
      standing: '/ˈstændɪŋ/',
      small: '/smɔːl/',
    },
  },
  {
    id: 'raining-cats-dogs',
    title: 'Raining cats and dogs',
    source: 'Common idiom',
    category: 'idioms',
    text: "When it's raining cats and dogs, it's raining very heavily. You would never actually see cats and dogs falling from the sky, of course. This expression simply means there is extremely heavy rainfall.",
    ipa: {
      when: '/wɛn/',
      it: '/ɪt/',
      is: '/ɪz/',
      raining: '/ˈreɪnɪŋ/',
      cats: '/kæts/',
      and: '/ænd/',
      dogs: '/dɔːɡz/',
      very: '/ˈvɛri/',
      heavily: '/ˈhɛvɪli/',
      you: '/juː/',
      would: '/wʊd/',
      never: '/ˈnɛvər/',
      actually: '/ˈæktʃuəli/',
      see: '/siː/',
      falling: '/ˈfɔːlɪŋ/',
      from: '/frʌm/',
      the: '/ðə/',
      sky: '/skaɪ/',
      of: '/ʌv/',
      course: '/kɔːrs/',
      this: '/ðɪs/',
      expression: '/ɪkˈsprɛʃən/',
      simply: '/ˈsɪmpli/',
      means: '/miːnz/',
      there: '/ðɛr/',
      extremely: '/ɪkˈstriːmli/',
      rainfall: '/ˈreɪnˌfɔːl/',
    },
  },
  {
    id: 'self-reliance',
    title: 'Self-Reliance',
    source: 'Ralph Waldo Emerson, 1841',
    category: 'essays',
    text: "Whoso would be a man must be a nonconformist. He who would gather immortal palms must not be hindered by the name of goodness, but must explore if it be goodness. Nothing can bring you peace but yourself. Nothing can bring you peace but the triumph of principles.",
    ipa: {
      whoso: '/ˈhuːˌsoʊ/',
      would: '/wʊd/',
      be: '/biː/',
      a: '/ə/',
      man: '/mæn/',
      must: '/mʌst/',
      nonconformist: '/ˌnɒnkənˈfɔːrmɪst/',
      he: '/hiː/',
      who: '/huː/',
      gather: '/ˈɡæðər/',
      immortal: '/ɪˈmɔːrtəl/',
      palms: '/pɑːmz/',
      not: '/nɒt/',
      hindered: '/ˈhɪndərd/',
      by: '/baɪ/',
      the: '/ðə/',
      name: '/neɪm/',
      of: '/ʌv/',
      goodness: '/ˈɡʊdnɪs/',
      but: '/bʌt/',
      explore: '/ɪkˈsplɔːr/',
      if: '/ɪf/',
      it: '/ɪt/',
      nothing: '/ˈnʌθɪŋ/',
      can: '/kæn/',
      bring: '/brɪŋ/',
      you: '/juː/',
      peace: '/piːs/',
      yourself: '/jɔːrˈsɛlf/',
      triumph: '/ˈtraɪəmf/',
      principles: '/ˈprɪnsəpəlz/',
    },
  },
  {
    id: 'room-of-ones-own',
    title: 'A Room of One\'s Own',
    source: 'Virginia Woolf, 1929',
    category: 'essays',
    text: "A woman must have money and a room of her own if she is to write fiction seriously. Here I am asking why women have not written the kind of books that men have written, and why I am laying stress on money when the case is about writing.",
    ipa: {
      a: '/ə/',
      woman: '/ˈwʊmən/',
      must: '/mʌst/',
      have: '/hæv/',
      money: '/ˈmʌni/',
      and: '/ænd/',
      room: '/ruːm/',
      of: '/ʌv/',
      her: '/hɜːr/',
      own: '/oʊn/',
      if: '/ɪf/',
      she: '/ʃiː/',
      is: '/ɪz/',
      to: '/tuː/',
      write: '/raɪt/',
      fiction: '/ˈfɪkʃən/',
      seriously: '/ˈsɪrɪəsli/',
      here: '/hɪr/',
      i: '/aɪ/',
      am: '/æm/',
      asking: '/ˈæskɪŋ/',
      why: '/waɪ/',
      women: '/ˈwɪmɪn/',
      not: '/nɒt/',
      written: '/ˈrɪtən/',
      the: '/ðə/',
      kind: '/kaɪnd/',
      books: '/bʊks/',
      that: '/ðæt/',
      men: '/mɛn/',
      laying: '/ˈleɪɪŋ/',
      stress: '/strɛs/',
      on: '/ɑːn/',
      when: '/wɛn/',
      case: '/keɪs/',
      about: '/əˈbaʊt/',
      writing: '/ˈraɪtɪŋ/',
    },
  },
  {
    id: 'once-more-lake',
    title: 'Once More to the Lake',
    source: 'E.B. White, 1941',
    category: 'essays',
    text: "One summer, along about the first of August, when the early morning air smells of the possibility of autumn, I like to slip away for a few weeks' vacation. I take the boy and we go to the lake where my family has always gone for generations.",
    ipa: {
      one: '/wʌn/',
      summer: '/ˈsʌmər/',
      along: '/əˈlɔːŋ/',
      about: '/əˈbaʊt/',
      the: '/ðə/',
      first: '/fɜːrst/',
      of: '/ʌv/',
      august: '/ˈɔːɡəst/',
      when: '/wɛn/',
      early: '/ˈɜːrli/',
      morning: '/ˈmɔːrnɪŋ/',
      air: '/ɛr/',
      smells: '/smɛlz/',
      possibility: '/ˌpɒsəˈbɪləti/',
      autumn: '/ˈɔːtəm/',
      i: '/aɪ/',
      like: '/laɪk/',
      to: '/tuː/',
      slip: '/slɪp/',
      away: '/əˈweɪ/',
      for: '/fɔːr/',
      a: '/ə/',
      few: '/fjuː/',
      weeks: '/wiːks/',
      vacation: '/veɪˈkeɪʃən/',
      take: '/teɪk/',
      boy: '/bɔɪ/',
      and: '/ænd/',
      we: '/wiː/',
      go: '/ɡoʊ/',
      where: '/wɛr/',
      my: '/maɪ/',
      family: '/ˈfæmɪli/',
      has: '/hæz/',
      always: '/ˈɔːlweɪz/',
      gone: '/ɡɔːn/',
      generations: '/ˌdʒɛnəˈreɪʃənz/',
    },
  },
  {
    id: 'hobbit-door',
    title: 'The Hobbit',
    source: 'J.R.R. Tolkien, 1937',
    category: 'literature',
    text: "It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.",
    ipa: {
      it: '/ɪt/',
      is: '/ɪz/',
      a: '/ə/',
      dangerous: '/ˈdeɪndʒərəs/',
      business: '/ˈbɪznɪs/',
      frodo: '/ˈfroʊdoʊ/',
      going: '/ˈɡoʊɪŋ/',
      out: '/aʊt/',
      your: '/jɔːr/',
      door: '/dɔːr/',
      you: '/juː/',
      step: '/stɛp/',
      onto: '/ˈɑːntuː/',
      the: '/ðə/',
      road: '/roʊd/',
      and: '/ænd/',
      if: '/ɪf/',
      "don't": '/doʊnt/',
      keep: '/kiːp/',
      feet: '/fiːt/',
      there: '/ðɛr/',
      no: '/noʊ/',
      knowing: '/ˈnoʊɪŋ/',
      where: '/wɛr/',
      might: '/maɪt/',
      be: '/biː/',
      swept: '/swɛpt/',
      off: '/ɔːf/',
      to: '/tuː/',
    },
  },
  {
    id: 'kung-fu-panda-present',
    title: 'Kung Fu Panda',
    source: 'Kung Fu Panda, 2008',
    category: 'movies-tv',
    text: "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
    youtubeId: 'PSBfcpqICvY',
    youtubeStart: 66,
    youtubeEnd: 88,
    ipa: {
      yesterday: '/ˈjɛstərdeɪ/',
      is: '/ɪz/',
      history: '/ˈhɪstəri/',
      tomorrow: '/təˈmɑːroʊ/',
      a: '/ə/',
      mystery: '/ˈmɪstəri/',
      but: '/bʌt/',
      today: '/təˈdeɪ/',
      gift: '/ɡɪft/',
      that: '/ðæt/',
      why: '/waɪ/',
      it: '/ɪt/',
      called: '/kɔːld/',
      the: '/ðə/',
      present: '/ˈprɛzənt/',
    },
  },
  {
    id: 'lion-king-future',
    title: 'The Lion King',
    source: 'The Lion King, 1994',
    category: 'movies-tv',
    text: "The past can hurt. But the way I see it, you can either run from it or learn from it. You see? So what are you going to do?",
    youtubeId: 'dZfGTL2PY3E',
    youtubeStart: 31,
    youtubeEnd: 0,
    ipa: {
      the: '/ðə/',
      past: '/pæst/',
      can: '/kæn/',
      hurt: '/hɜːrt/',
      but: '/bʌt/',
      way: '/weɪ/',
      i: '/aɪ/',
      see: '/siː/',
      it: '/ɪt/',
      you: '/juː/',
      either: '/ˈiːðər/',
      run: '/rʌn/',
      from: '/frʌm/',
      or: '/ɔːr/',
      learn: '/lɜːrn/',
      so: '/soʊ/',
      what: '/wʌt/',
      are: '/ɑːr/',
      going: '/ˈɡoʊɪŋ/',
      to: '/tuː/',
      do: '/duː/',
    },
  },
  {
    id: 'jfk-inaugural',
    title: 'Inaugural Address',
    source: 'John F. Kennedy, 1961',
    category: 'speeches',
    text: "Ask not what your country can do for you—ask what you can do for your country. Let us never negotiate out of fear. But let us never fear to negotiate. Let both sides seek to invoke the wonders of science instead of its terrors.",
    ipa: {
      ask: '/æsk/',
      not: '/nɒt/',
      what: '/wʌt/',
      your: '/jɔːr/',
      country: '/ˈkʌntri/',
      can: '/kæn/',
      do: '/duː/',
      for: '/fɔːr/',
      you: '/juː/',
      let: '/lɛt/',
      us: '/ʌs/',
      never: '/ˈnɛvər/',
      negotiate: '/nɪˈɡoʊʃieɪt/',
      out: '/aʊt/',
      of: '/ʌv/',
      fear: '/fɪr/',
      but: '/bʌt/',
      to: '/tuː/',
      both: '/boʊθ/',
      sides: '/saɪdz/',
      seek: '/siːk/',
      invoke: '/ɪnˈvoʊk/',
      the: '/ðə/',
      wonders: '/ˈwʌndərz/',
      science: '/ˈsaɪəns/',
      instead: '/ɪnˈstɛd/',
      its: '/ɪts/',
      terrors: '/ˈtɛrərz/',
    },
  },
  {
    id: 'forrest-gump-chocolates',
    title: 'Forrest Gump',
    source: 'Robert Zemeckis, 1994',
    category: 'movies-tv',
    text: "Mama always said life was like a box of chocolates. You never know what you're gonna get. She always had a way of explaining things so I could understand them.",
    ipa: {
      mama: '/ˈmɑːmə/',
      always: '/ˈɔːlweɪz/',
      said: '/sɛd/',
      life: '/laɪf/',
      was: '/wəz/',
      like: '/laɪk/',
      a: '/ə/',
      box: '/bɒks/',
      of: '/ʌv/',
      chocolates: '/ˈtʃɒklɪts/',
      you: '/juː/',
      never: '/ˈnɛvər/',
      know: '/noʊ/',
      what: '/wʌt/',
      gonna: '/ˈɡɒnə/',
      get: '/ɡɛt/',
      she: '/ʃiː/',
      had: '/hæd/',
      way: '/weɪ/',
      explaining: '/ɪkˈspleɪnɪŋ/',
      things: '/θɪŋz/',
      so: '/soʊ/',
      i: '/aɪ/',
      could: '/kʊd/',
      understand: '/ˌʌndərˈstænd/',
      them: '/ðɛm/',
    },
  },
  {
    id: 'brave-fate',
    title: 'Brave',
    source: 'Mark Andrews & Brenda Chapman, 2012',
    category: 'movies-tv',
    text: "There are those who say fate is something beyond our command. That destiny is not our own. But I know better. Our fate lives within us. You only have to be brave enough to see it.",
    ipa: {
      there: '/ðɛr/',
      are: '/ɑːr/',
      those: '/ðoʊz/',
      who: '/huː/',
      say: '/seɪ/',
      fate: '/feɪt/',
      is: '/ɪz/',
      something: '/ˈsʌmθɪŋ/',
      beyond: '/bɪˈjɒnd/',
      our: '/aʊər/',
      command: '/kəˈmænd/',
      that: '/ðæt/',
      destiny: '/ˈdɛstɪni/',
      not: '/nɒt/',
      own: '/oʊn/',
      but: '/bʌt/',
      i: '/aɪ/',
      know: '/noʊ/',
      better: '/ˈbɛtər/',
      lives: '/lɪvz/',
      within: '/wɪˈðɪn/',
      us: '/ʌs/',
      you: '/juː/',
      only: '/ˈoʊnli/',
      have: '/hæv/',
      to: '/tuː/',
      be: '/biː/',
      brave: '/breɪv/',
      enough: '/ɪˈnʌf/',
      see: '/siː/',
      it: '/ɪt/',
    },
  },
  {
    id: 'wizard-of-oz-home',
    title: 'The Wizard of Oz',
    source: 'Victor Fleming, 1939',
    category: 'movies-tv',
    text: "Toto, I've a feeling we're not in Kansas anymore. If I ever go looking for my heart's desire again, I won't look any further than my own backyard. Because if it isn't there, I never really lost it to begin with.",
    ipa: {
      toto: '/ˈtoʊtoʊ/',
      feeling: '/ˈfiːlɪŋ/',
      we: '/wiː/',
      not: '/nɒt/',
      in: '/ɪn/',
      kansas: '/ˈkænzəs/',
      anymore: '/ˌɛniˈmɔːr/',
      if: '/ɪf/',
      ever: '/ˈɛvər/',
      go: '/ɡoʊ/',
      looking: '/ˈlʊkɪŋ/',
      for: '/fɔːr/',
      my: '/maɪ/',
      heart: '/hɑːrt/',
      desire: '/dɪˈzaɪər/',
      again: '/əˈɡɛn/',
      look: '/lʊk/',
      further: '/ˈfɜːrðər/',
      than: '/ðæn/',
      own: '/oʊn/',
      backyard: '/ˈbækjɑːrd/',
      because: '/bɪˈkɔːz/',
      there: '/ðɛr/',
      never: '/ˈnɛvər/',
      really: '/ˈriːəli/',
      lost: '/lɔːst/',
      it: '/ɪt/',
      begin: '/bɪˈɡɪn/',
      with: '/wɪð/',
    },
  },
  {
    id: 'pride-and-prejudice',
    title: 'Pride and Prejudice',
    source: 'Jane Austen, 1813',
    category: 'literature',
    text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be, this truth is so well fixed in the minds of the surrounding families.",
    ipa: {
      it: '/ɪt/',
      is: '/ɪz/',
      a: '/ə/',
      truth: '/truːθ/',
      universally: '/ˌjuːnɪˈvɜːrsəli/',
      acknowledged: '/əkˈnɒlɪdʒd/',
      that: '/ðæt/',
      single: '/ˈsɪŋɡəl/',
      man: '/mæn/',
      in: '/ɪn/',
      possession: '/pəˈzɛʃən/',
      of: '/ʌv/',
      good: '/ɡʊd/',
      fortune: '/ˈfɔːrtʃən/',
      must: '/mʌst/',
      be: '/biː/',
      want: '/wɑːnt/',
      wife: '/waɪf/',
      however: '/haʊˈɛvər/',
      little: '/ˈlɪtəl/',
      known: '/noʊn/',
      feelings: '/ˈfiːlɪŋz/',
      or: '/ɔːr/',
      views: '/vjuːz/',
      such: '/sʌtʃ/',
      may: '/meɪ/',
      this: '/ðɪs/',
      so: '/soʊ/',
      well: '/wɛl/',
      fixed: '/fɪkst/',
      the: '/ðə/',
      minds: '/maɪndz/',
      surrounding: '/səˈraʊndɪŋ/',
      families: '/ˈfæmɪlɪz/',
    },
  },
  {
    id: 'their-eyes-were-watching',
    title: 'Their Eyes Were Watching God',
    source: 'Zora Neale Hurston, 1937',
    category: 'literature',
    text: "Ships at a distance have every man's wish on board. For some they come in with the tide. For others they sail forever on the horizon, never out of sight, never landing until the Watcher turns his eyes away in resignation.",
    ipa: {
      ships: '/ʃɪps/',
      at: '/æt/',
      a: '/ə/',
      distance: '/ˈdɪstəns/',
      have: '/hæv/',
      every: '/ˈɛvri/',
      wish: '/wɪʃ/',
      on: '/ɒn/',
      board: '/bɔːrd/',
      for: '/fɔːr/',
      some: '/sʌm/',
      they: '/ðeɪ/',
      come: '/kʌm/',
      in: '/ɪn/',
      with: '/wɪð/',
      the: '/ðə/',
      tide: '/taɪd/',
      others: '/ˈʌðərz/',
      sail: '/seɪl/',
      forever: '/fərˈɛvər/',
      horizon: '/həˈraɪzən/',
      never: '/ˈnɛvər/',
      out: '/aʊt/',
      of: '/ʌv/',
      sight: '/saɪt/',
      landing: '/ˈlændɪŋ/',
      until: '/ʌnˈtɪl/',
      watcher: '/ˈwɒtʃər/',
      turns: '/tɜːrnz/',
      his: '/hɪz/',
      eyes: '/aɪz/',
      away: '/əˈweɪ/',
      resignation: '/ˌrɛzɪɡˈneɪʃən/',
    },
  },
  {
    id: 'still-i-rise',
    title: 'Still I Rise',
    source: 'Maya Angelou, 1978',
    category: 'literature',
    text: "You may write me down in history with your bitter, twisted lies. You may trod me in the very dirt. But still, like dust, I'll rise. Just like moons and like suns, with the certainty of tides, just like hopes springing high, still I'll rise.",
    ipa: {
      you: '/juː/',
      may: '/meɪ/',
      write: '/raɪt/',
      me: '/miː/',
      down: '/daʊn/',
      in: '/ɪn/',
      history: '/ˈhɪstəri/',
      with: '/wɪð/',
      your: '/jɔːr/',
      bitter: '/ˈbɪtər/',
      twisted: '/ˈtwɪstɪd/',
      lies: '/laɪz/',
      trod: '/trɒd/',
      the: '/ðə/',
      very: '/ˈvɛri/',
      dirt: '/dɜːrt/',
      but: '/bʌt/',
      still: '/stɪl/',
      like: '/laɪk/',
      dust: '/dʌst/',
      rise: '/raɪz/',
      just: '/dʒʌst/',
      moons: '/muːnz/',
      and: '/ænd/',
      suns: '/sʌnz/',
      certainty: '/ˈsɜːrtənti/',
      of: '/ʌv/',
      tides: '/taɪdz/',
      hopes: '/hoʊps/',
      springing: '/ˈsprɪŋɪŋ/',
      high: '/haɪ/',
    },
  },
]
