export interface Passage {
  id: string
  title: string
  source: string
  text: string
  ipa?: Record<string, string>
}

export const SAMPLE_PASSAGES: Passage[] = [
  {
    id: 'interstellar',
    title: 'Interstellar',
    source: 'Christopher Nolan, 2014',
    text: "We used to look up at the sky and wonder at our place in the stars. Now we just look down, and worry about our place in the dirt.",
    ipa: {
      we: '/wiː/',
      used: '/juːzd/',
      to: '/tuː/',
      look: '/lʊk/',
      up: '/ʌp/',
      at: '/æt/',
      the: '/ðə/',
      sky: '/skaɪ/',
      and: '/ænd/',
      wonder: '/ˈwʌndər/',
      our: '/aʊər/',
      place: '/pleɪs/',
      in: '/ɪn/',
      stars: '/stɑːrz/',
      now: '/naʊ/',
      just: '/dʒʌst/',
      down: '/daʊn/',
      worry: '/ˈwɜːri/',
      about: '/əˈbaʊt/',
      dirt: '/dɜːrt/',
    },
  },
  {
    id: 'great-dictator',
    title: 'The Great Dictator',
    source: 'Charlie Chaplin, 1940',
    text: "You, the people, have the power to make this life free and beautiful, to make this life a wonderful adventure. Let us fight to free the world, to do away with national barriers, to do away with greed, with hate and intolerance. Let us fight for a world of reason, a world where science and progress will lead to all men's happiness.",
    ipa: {
      you: '/juː/',
      the: '/ðə/',
      people: '/ˈpiːpəl/',
      have: '/hæv/',
      power: '/ˈpaʊər/',
      make: '/meɪk/',
      this: '/ðɪs/',
      life: '/laɪf/',
      free: '/friː/',
      and: '/ænd/',
      beautiful: '/ˈbjuːtɪfəl/',
      wonderful: '/ˈwʌndərfəl/',
      adventure: '/ədˈventʃər/',
      let: '/lɛt/',
      us: '/ʌs/',
      fight: '/faɪt/',
      world: '/wɜːrld/',
      do: '/duː/',
      away: '/əˈweɪ/',
      with: '/wɪð/',
      national: '/ˈnæʃənəl/',
      barriers: '/ˈbæriərz/',
      greed: '/ɡriːd/',
      hate: '/heɪt/',
      intolerance: '/ɪnˈtɒlərəns/',
      for: '/fɔːr/',
      reason: '/ˈriːzən/',
      where: '/wɛr/',
      science: '/ˈsaɪəns/',
      progress: '/ˈprɒɡrɛs/',
      will: '/wɪl/',
      lead: '/liːd/',
      all: '/ɔːl/',
      happiness: '/ˈhæpɪnəs/',
    },
  },
  {
    id: 'rocky-balboa',
    title: 'Rocky Balboa',
    source: 'Sylvester Stallone, 2006',
    text: "Let me tell you something you already know. The world ain't all sunshine and rainbows, it's a very mean and nasty place and I don't care how tough you are it will beat you to your knees and keep you there permanently if you let it. You, me, nobody is gonna hit as hard as life! But it ain't about how hard you can hit, it's about how hard you can get hit and keep movin' forward, how much you can take...and keep movin' forward. That's how winning is done!",
    ipa: {
      let: '/lɛt/',
      me: '/miː/',
      tell: '/tɛl/',
      you: '/juː/',
      something: '/ˈsʌmθɪŋ/',
      already: '/ɔːlˈrɛdi/',
      know: '/noʊ/',
      the: '/ðə/',
      world: '/wɜːrld/',
      all: '/ɔːl/',
      sunshine: '/ˈsʌnʃaɪn/',
      and: '/ænd/',
      rainbows: '/ˈreɪnboʊz/',
      very: '/ˈvɛri/',
      mean: '/miːn/',
      nasty: '/ˈnæsti/',
      place: '/pleɪs/',
      care: '/kɛr/',
      how: '/haʊ/',
      tough: '/tʌf/',
      beat: '/biːt/',
      knees: '/niːz/',
      keep: '/kiːp/',
      permanently: '/ˈpɜːrmənəntli/',
      nobody: '/ˈnoʊbədi/',
      gonna: '/ˈɡɒnə/',
      hit: '/hɪt/',
      hard: '/hɑːrd/',
      life: '/laɪf/',
      but: '/bʌt/',
      about: '/əˈbaʊt/',
      forward: '/ˈfɔːrwərd/',
      much: '/mʌtʃ/',
      take: '/teɪk/',
      winning: '/ˈwɪnɪŋ/',
      done: '/dʌn/',
    },
  },
]
