export type PassageCategory = 'movies-tv' | 'speeches' | 'idioms' | 'tongue-twisters' | 'custom'

export const PASSAGE_CATEGORIES: PassageCategory[] = ['movies-tv', 'speeches', 'idioms', 'tongue-twisters', 'custom']

export const CATEGORY_LABELS: Record<PassageCategory, string> = {
  'movies-tv': 'Movie & TV Quotes',
  'speeches': 'Famous Speeches',
  'idioms': 'Idioms',
  'tongue-twisters': 'Tongue Twisters',
  'custom': 'Custom',
}

export interface Passage {
  id: string
  title: string
  source: string
  text: string
  category: PassageCategory
  ipa?: Record<string, string>
}

export const SAMPLE_PASSAGES: Passage[] = [
  {
    id: 'interstellar',
    title: 'Interstellar',
    source: 'Christopher Nolan, 2014',
    category: 'movies-tv',
    text: "We used to look up at the sky and wonder at our place in the stars. Now we just look down, and worry about our place in the dirt.",
    ipa: {
      we: '/wiː/',
      used: '/juːzd/',
      to: '/tuː/',
      look: '/lʊk/',
      up: '/ʌp/',
      at: '/æt/',
      the: '/ðə/',
      sky: '/skaɪ/',
      and: '/ænd/',
      wonder: '/ˈwʌndər/',
      our: '/aʊər/',
      place: '/pleɪs/',
      in: '/ɪn/',
      stars: '/stɑːrz/',
      now: '/naʊ/',
      just: '/dʒʌst/',
      down: '/daʊn/',
      worry: '/ˈwɜːri/',
      about: '/əˈbaʊt/',
      dirt: '/dɜːrt/',
    },
  },
  {
    id: 'great-dictator',
    title: 'The Great Dictator',
    source: 'Charlie Chaplin, 1940',
    category: 'movies-tv',
    text: "You, the people, have the power to make this life free and beautiful, to make this life a wonderful adventure. Let us fight to free the world, to do away with national barriers, to do away with greed, with hate and intolerance. Let us fight for a world of reason, a world where science and progress will lead to all men's happiness.",
    ipa: {
      you: '/juː/',
      the: '/ðə/',
      people: '/ˈpiːpəl/',
      have: '/hæv/',
      power: '/ˈpaʊər/',
      make: '/meɪk/',
      this: '/ðɪs/',
      life: '/laɪf/',
      free: '/friː/',
      and: '/ænd/',
      beautiful: '/ˈbjuːtɪfəl/',
      wonderful: '/ˈwʌndərfəl/',
      adventure: '/ədˈventʃər/',
      let: '/lɛt/',
      us: '/ʌs/',
      fight: '/faɪt/',
      world: '/wɜːrld/',
      do: '/duː/',
      away: '/əˈweɪ/',
      with: '/wɪð/',
      national: '/ˈnæʃənəl/',
      barriers: '/ˈbæriərz/',
      greed: '/ɡriːd/',
      hate: '/heɪt/',
      intolerance: '/ɪnˈtɒlərəns/',
      for: '/fɔːr/',
      reason: '/ˈriːzən/',
      where: '/wɛr/',
      science: '/ˈsaɪəns/',
      progress: '/ˈprɒɡrɛs/',
      will: '/wɪl/',
      lead: '/liːd/',
      all: '/ɔːl/',
      happiness: '/ˈhæpɪnəs/',
    },
  },
  {
    id: 'rocky-balboa',
    title: 'Rocky Balboa',
    source: 'Sylvester Stallone, 2006',
    category: 'movies-tv',
    text: "Let me tell you something you already know. The world ain't all sunshine and rainbows, it's a very mean and nasty place and I don't care how tough you are it will beat you to your knees and keep you there permanently if you let it. You, me, nobody is gonna hit as hard as life! But it ain't about how hard you can hit, it's about how hard you can get hit and keep movin' forward, how much you can take...and keep movin' forward. That's how winning is done!",
    ipa: {
      let: '/lɛt/',
      me: '/miː/',
      tell: '/tɛl/',
      you: '/juː/',
      something: '/ˈsʌmθɪŋ/',
      already: '/ɔːlˈrɛdi/',
      know: '/noʊ/',
      the: '/ðə/',
      world: '/wɜːrld/',
      all: '/ɔːl/',
      sunshine: '/ˈsʌnʃaɪn/',
      and: '/ænd/',
      rainbows: '/ˈreɪnboʊz/',
      very: '/ˈvɛri/',
      mean: '/miːn/',
      nasty: '/ˈnæsti/',
      place: '/pleɪs/',
      care: '/kɛr/',
      how: '/haʊ/',
      tough: '/tʌf/',
      beat: '/biːt/',
      knees: '/niːz/',
      keep: '/kiːp/',
      permanently: '/ˈpɜːrmənəntli/',
      nobody: '/ˈnoʊbədi/',
      gonna: '/ˈɡɒnə/',
      hit: '/hɪt/',
      hard: '/hɑːrd/',
      life: '/laɪf/',
      but: '/bʌt/',
      about: '/əˈbaʊt/',
      forward: '/ˈfɔːrwərd/',
      much: '/mʌtʃ/',
      take: '/teɪk/',
      winning: '/ˈwɪnɪŋ/',
      done: '/dʌn/',
    },
  },
  {
    id: 'steve-jobs-stanford',
    title: 'Stanford Commencement',
    source: 'Steve Jobs, 2005',
    category: 'speeches',
    text: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma, which is living with the results of other people's thinking. Don't let the noise of others' opinions drown out your own inner voice. And most importantly, have the courage to follow your heart and intuition.",
    ipa: {
      your: '/jɔːr/',
      time: '/taɪm/',
      is: '/ɪz/',
      limited: '/ˈlɪmɪtɪd/',
      so: '/soʊ/',
      "don't": '/doʊnt/',
      waste: '/weɪst/',
      it: '/ɪt/',
      living: '/ˈlɪvɪŋ/',
      someone: '/ˈsʌmwʌn/',
      else: '/ɛls/',
      life: '/laɪf/',
      be: '/biː/',
      trapped: '/træpt/',
      by: '/baɪ/',
      dogma: '/ˈdɒɡmə/',
      which: '/wɪtʃ/',
      results: '/rɪˈzʌlts/',
      of: '/ʌv/',
      other: '/ˈʌðər/',
      people: '/ˈpiːpəl/',
      thinking: '/ˈθɪŋkɪŋ/',
      let: '/lɛt/',
      the: '/ðə/',
      noise: '/nɔɪz/',
      opinions: '/əˈpɪnjənz/',
      drown: '/draʊn/',
      out: '/aʊt/',
      own: '/oʊn/',
      inner: '/ˈɪnər/',
      voice: '/vɔɪs/',
      and: '/ænd/',
      most: '/moʊst/',
      importantly: '/ɪmˈpɔːrtəntli/',
      have: '/hæv/',
      courage: '/ˈkɜːrɪdʒ/',
      to: '/tuː/',
      follow: '/ˈfɒloʊ/',
      heart: '/hɑːrt/',
      intuition: '/ˌɪntjuˈɪʃən/',
    },
  },
  {
    id: 'inigo-montoya',
    title: 'The Princess Bride',
    source: 'William Goldman, 1987',
    category: 'movies-tv',
    text: "Hello. My name is Inigo Montoya. You killed my father. Prepare to die. I have been in the revenge business so long, now that it's over, I do not know what to do with the rest of my life.",
    ipa: {
      hello: '/həˈloʊ/',
      my: '/maɪ/',
      name: '/neɪm/',
      is: '/ɪz/',
      inigo: '/ˈɪnɪɡoʊ/',
      montoya: '/mɒnˈtɔɪə/',
      you: '/juː/',
      killed: '/kɪld/',
      father: '/ˈfɑːðər/',
      prepare: '/prɪˈpɛr/',
      to: '/tuː/',
      die: '/daɪ/',
      i: '/aɪ/',
      have: '/hæv/',
      been: '/bɪn/',
      in: '/ɪn/',
      the: '/ðə/',
      revenge: '/rɪˈvɛndʒ/',
      business: '/ˈbɪznɪs/',
      so: '/soʊ/',
      long: '/lɒŋ/',
      now: '/naʊ/',
      that: '/ðæt/',
      it: '/ɪt/',
      over: '/ˈoʊvər/',
      do: '/duː/',
      not: '/nɒt/',
      know: '/noʊ/',
      what: '/wʌt/',
      with: '/wɪð/',
      rest: '/rɛst/',
      of: '/ʌv/',
      life: '/laɪf/',
    },
  },
  {
    id: 'i-have-a-dream',
    title: 'I Have a Dream',
    source: 'Martin Luther King Jr., 1963',
    category: 'speeches',
    text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed: we hold these truths to be self-evident, that all men are created equal. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.",
    ipa: {
      i: '/aɪ/',
      have: '/hæv/',
      a: '/ə/',
      dream: '/driːm/',
      that: '/ðæt/',
      one: '/wʌn/',
      day: '/deɪ/',
      this: '/ðɪs/',
      nation: '/ˈneɪʃən/',
      will: '/wɪl/',
      rise: '/raɪz/',
      up: '/ʌp/',
      and: '/ænd/',
      live: '/lɪv/',
      out: '/aʊt/',
      the: '/ðə/',
      true: '/truː/',
      meaning: '/ˈmiːnɪŋ/',
      of: '/ʌv/',
      its: '/ɪts/',
      creed: '/kriːd/',
      we: '/wiː/',
      hold: '/hoʊld/',
      these: '/ðiːz/',
      truths: '/truːθs/',
      to: '/tuː/',
      be: '/biː/',
      self: '/sɛlf/',
      evident: '/ˈɛvɪdənt/',
      all: '/ɔːl/',
      men: '/mɛn/',
      are: '/ɑːr/',
      created: '/kriˈeɪtɪd/',
      equal: '/ˈiːkwəl/',
      my: '/maɪ/',
      four: '/fɔːr/',
      little: '/ˈlɪtəl/',
      children: '/ˈtʃɪldrən/',
      in: '/ɪn/',
      where: '/wɛr/',
      not: '/nɒt/',
      judged: '/dʒʌdʒd/',
      by: '/baɪ/',
      color: '/ˈkʌlər/',
      their: '/ðɛr/',
      skin: '/skɪn/',
      but: '/bʌt/',
      content: '/ˈkɒntɛnt/',
      character: '/ˈkærɪktər/',
    },
  },
  {
    id: 'she-sells-seashells',
    title: 'She Sells Seashells',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "She sells seashells by the seashore. The shells she sells are surely seashells. So if she sells shells on the seashore, I'm sure she sells seashore shells.",
    ipa: {
      she: '/ʃiː/',
      sells: '/sɛlz/',
      seashells: '/ˈsiːʃɛlz/',
      by: '/baɪ/',
      the: '/ðə/',
      seashore: '/ˈsiːʃɔːr/',
      shells: '/ʃɛlz/',
      are: '/ɑːr/',
      surely: '/ˈʃʊərli/',
      so: '/soʊ/',
      if: '/ɪf/',
      on: '/ɒn/',
      sure: '/ʃʊər/',
    },
  },
  {
    id: 'peter-piper',
    title: 'Peter Piper',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where's the peck of pickled peppers Peter Piper picked?",
    ipa: {
      peter: '/ˈpiːtər/',
      piper: '/ˈpaɪpər/',
      picked: '/pɪkt/',
      a: '/ə/',
      peck: '/pɛk/',
      of: '/ʌv/',
      pickled: '/ˈpɪkəld/',
      peppers: '/ˈpɛpərz/',
      if: '/ɪf/',
      where: '/wɛr/',
      the: '/ðə/',
    },
  },
  {
    id: 'woodchuck',
    title: 'How Much Wood',
    source: 'Traditional',
    category: 'tongue-twisters',
    text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.",
    ipa: {
      how: '/haʊ/',
      much: '/mʌtʃ/',
      wood: '/wʊd/',
      would: '/wʊd/',
      a: '/ə/',
      woodchuck: '/ˈwʊdtʃʌk/',
      chuck: '/tʃʌk/',
      if: '/ɪf/',
      could: '/kʊd/',
      he: '/hiː/',
      as: '/æz/',
      and: '/ænd/',
    },
  },
]
